name: Check changes

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt -qq update
        sudo apt install -y libmagic1
        python -m pip install --upgrade pip
        python -m pip install jsonschema python-magic
    - name: Check changes
      run: |
        ./test-pr.py
